#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ -z "$BROWSER" && "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

if [[ -z "$EDITOR" ]]; then
  export EDITOR='nvim'
fi
if [[ -z "$VISUAL" ]]; then
  export VISUAL='nvim'
fi
if [[ -z "$PAGER" ]]; then
  export PAGER='less'
fi

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
  # export LANG='ja_JP.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  $HOME/{,.}{,s}bin(N)
  $HOME/go/bin(N)
  $HOME/Library/Application Support/multipass/bin(N)
  $HOME/Library/Android/sdk/tools(N)
  $HOME/Library/Android/sdk/platform-tools(N)
  $HOME/Library/Android/sdk/cmdline-tools/latest/bin(N)
  $HOME/Library/Android/sdk/build-tools/30.0.3(N)
  /opt/{homebrew,local}/{,s}bin(N)
  /usr/local/{,s}bin(N)
  /usr/local/opt/coreutils/libexec/gnubin(N)
  $path
)

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X to enable it.
if [[ -z "$LESS" ]]; then
  export LESS='-g -i -M -R -S -w -X -z-4'
fi

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if [[ -z "$LESSOPEN" ]] && (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

if [[ -o interactive ]]; then
  export CLICOLOR=1
  export LSCOLORS=GxFxCxDxBxegedabagaced
  export KEYTIMEOUT=1
fi


# ruby bundler
# https://bundler.io/man/bundle-config.1.html
export BUNDLE_GITHUB__COM=****************************************:x-oauth-basic

# mysql
export BUNDLE_BUILD__MYSQL=--with-mysql-config=$(which mysql_config)

# gem install mysql2 -v '0.5.3' --source 'https://rubygems.org/'
# export RUBY_CONFIGURE_OPTS="--with-openssl-dir=$(brew --prefix openssl)"
# export BUNDLE_BUILD__MYSQL2="--with-opt-dir=$(brew --prefix openssl)"

# install mysql2 gem by linking it with mysql 5.7 homebrew
# https://gist.github.com/rizalp/d776a08a538c5738e821265816ecbccd
# gem install mysql2 -v '0.5.3' -- --with-ldflags=-L/usr/local/opt/mysql/lib --with-cppflags=-I/usr/local/opt/mysql/include --with-ldflags=-L/usr/local/opt/openssl/lib --with-cppflags=-I/usr/local/opt/openssl/include
# gem install mysql2 -v '0.5.3' --source 'https://rubygems.org/'
