#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ -z "$BROWSER" && "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

if [[ -z "$EDITOR" ]]; then
  export EDITOR='nvim'
fi
if [[ -z "$VISUAL" ]]; then
  export VISUAL='nvim'
fi
if [[ -z "$PAGER" ]]; then
  export PAGER='less'
fi

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en'
  export LC_ALL=en_US.UTF-8
  # export LANG='ja_JP.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  $HOME/.local/bin(N)
  $HOME/{,.}{,s}bin(N)
  $HOME/go/bin(N)
  $HOME/Library/Application Support/multipass/bin(N)
  $HOME/Library/Android/sdk/tools(N)
  $HOME/Library/Android/sdk/platform-tools(N)
  $HOME/Library/Android/sdk/cmdline-tools/latest/bin(N)
  $HOME/Library/Android/sdk/build-tools/30.0.3(N)
  /opt/{homebrew,local}/{,s}bin(N)
  /opt/homebrew/opt/mysql@5.7/bin(N)
  /usr/local/{,s}bin(N)
  /usr/local/opt/coreutils/libexec/gnubin(N)
  $path
)

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X to enable it.
if [[ -z "$LESS" ]]; then
  export LESS='-g -i -M -R -S -w -X -z-4'
fi

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if [[ -z "$LESSOPEN" ]] && (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

if [[ -o interactive ]]; then
  export CLICOLOR=1
  export LSCOLORS=GxFxCxDxBxegedabagaced
  export KEYTIMEOUT=1
fi

if [[ -s "${ZDOTDIR:-$HOME}/.zprofile.private" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile.private"
fi


# ruby
## Ref: https://github.com/rbenv/ruby-build/wiki#macos

### For Ruby versions 2.x–3.0:
### brew install openssl@1.1 readline libyaml gmp
### export RUBY_CONFIGURE_OPTS="--with-openssl-dir=$(brew --prefix openssl@1.1)"

### For Ruby 3.1 and above requires OpenSSL 3
### brew install openssl@3 readline libyaml gmp
export RUBY_CONFIGURE_OPTS="--with-openssl-dir=$(brew --prefix openssl@3)"

## https://bundler.io/man/bundle-config.1.html
export BUNDLE_GITHUB__COM=$MY_GITHUB_PAT:x-oauth-basic
export BUNDLE_RUBYGEMS__PKG__GITHUB__COM=tronghiant:$MY_GITHUB_PAT


## About `mysql2` gem
## ref: https://gist.github.com/rizalp/d776a08a538c5738e821265816ecbccd
## to install mysql2 gem, we need to install its dependency: mysql (or mysql-client if you want smaller dependency size)
## brew install mysql-client@5.7
## Then we can install it `gem install 'mysql2:>=0.5.5'`

